baseURL: 'https://github.com/elliottau01/elliottau01.github.io/'
languageCode: en-us
title: Elliott And His World
theme: PaperMod

params:
  # homeInfoParams:
  #   Title: "Hello!"
  #   Content: Welcome to my blog!
  profileMode:
    enabled: true
    title: "<Title>" # optional default will be site title
    subtitle: "Hello! This is the website of Elliott Au. Welcome to my blog!"
    imageUrl: "img/icon.png" # optional
    imageTitle: "<title of image as alt>" # optional
    imageWidth: 120 # custom size
    imageHeight: 120 # custom size
    author: Elliott Au

  socialIcons:
    - name: instagram
      url: 'https://www.instagram.com/eli_ayl/'
    - name: linkedin
      url: 'https://www.linkedin.com/in/eliau'
    - name: github
      url: 'https://github.com/elliottau01'


  cover:
    linkFullImages: true

  ShowBreadCrumbs: false

  ShowReadingTime: true

  ShowPostNavLinks: true

  ShowToc: true


menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 10

    - identifier: projects
      name: Projects
      url: /projects/
      weight: 20

    - identifier: posts
      name: Posts
      url: /posts/
      weight: 30

    - identifier: contact
      name: Contact
      url: /contact/
      weight: 70

    - identifier: cv
      name: CV
      url: https://drive.google.com/file/d/1ca2rAsJFnvm2VJ_GfjB6o3HZzStWPoj2/view?usp=sharing
      weight: 80